import type {
  AdminProfile,
  DashboardResponse,
  IncidentReport,
  KycDocument,
  NotificationItem,
  RideRecord,
  SubscriptionPlan,
  SupportTicket,
  UserRecord,
} from "./types";

const wait = (duration = 180) =>
  new Promise((resolve) => {
    setTimeout(resolve, duration);
  });

export const hydrate = async <T>(data: T) => {
  await wait();
  return { data };
};

export const kycDocumentsPayload: KycDocument[] = [
  {
    id: "KYC-901",
    userId: "USR-901",
    user: {
      id: "USR-901",
      fullName: "Sandrine Kabeya",
      email: "sandrine.k@zwanga.cd",
      phoneNumber: "+243 829 555 410",
    },
    cniFrontUrl: "https://placehold.co/320x200?text=CNI+Front",
    cniBackUrl: "https://placehold.co/320x200?text=CNI+Back",
    selfieUrl: "https://placehold.co/160x160?text=Selfie",
    status: "pending",
    createdAt: "2025-11-17T06:55:00Z",
    updatedAt: "2025-11-17T06:55:00Z",
  },
  {
    id: "KYC-902",
    userId: "USR-904",
    user: {
      id: "USR-904",
      fullName: "David Luwezi",
      email: "david.l@zwanga.cd",
      phoneNumber: "+243 991 220 500",
    },
    cniFrontUrl: "https://placehold.co/320x200?text=CNI+Front",
    cniBackUrl: "https://placehold.co/320x200?text=CNI+Back",
    selfieUrl: "https://placehold.co/160x160?text=Selfie",
    status: "approved",
    reviewedBy: "Eugène Bosuku",
    reviewedAt: "2025-11-16T18:42:00Z",
    createdAt: "2025-11-16T16:20:00Z",
    updatedAt: "2025-11-16T18:42:00Z",
  },
  {
    id: "KYC-903",
    userId: "USR-905",
    user: {
      id: "USR-905",
      fullName: "Stéphanie Badika",
      email: "stephanie.b@zwanga.cd",
      phoneNumber: "+243 829 990 114",
    },
    cniFrontUrl: "https://placehold.co/320x200?text=CNI+Front",
    cniBackUrl: "https://placehold.co/320x200?text=CNI+Back",
    selfieUrl: "https://placehold.co/160x160?text=Selfie",
    status: "rejected",
    rejectionReason: "Document flou, merci de recharger.",
    reviewedBy: "Linda Kapinga",
    reviewedAt: "2025-11-15T13:10:00Z",
    createdAt: "2025-11-14T09:32:00Z",
    updatedAt: "2025-11-15T13:10:00Z",
  },
  {
    id: "KYC-904",
    userId: "USR-902",
    user: {
      id: "USR-902",
      fullName: "Patrick Mumbere",
      email: "patrick.m@zwanga.cd",
      phoneNumber: "+243 977 225 148",
    },
    cniFrontUrl: "https://placehold.co/320x200?text=CNI+Front",
    cniBackUrl: "https://placehold.co/320x200?text=CNI+Back",
    selfieUrl: "https://placehold.co/160x160?text=Selfie",
    status: "pending",
    createdAt: "2025-11-17T06:10:00Z",
    updatedAt: "2025-11-17T06:10:00Z",
  },
];

export const dashboardPayload: DashboardResponse = {
  greeting: "Bonjour Eugène, prêt pour la journée ?",
  dateRange: "Semaine du 10 → 16 nov.",
  metrics: [
    {
      id: "rides",
      label: "Trajets actifs",
      value: "1 284",
      delta: 12,
      trend: "up",
      helper: "vs hier",
    },
    {
      id: "kyc",
      label: "Dossiers KYC",
      value: "42 en revue",
      delta: -6,
      trend: "down",
      helper: "délai moyen 2h",
    },
    {
      id: "revenue",
      label: "Revenu net",
      value: "48 560 $",
      delta: 18,
      trend: "up",
      helper: "MTD",
    },
    {
      id: "support",
      label: "Tickets support",
      value: "18 ouverts",
      delta: 3,
      trend: "flat",
      helper: "SLA 1h24",
    },
  ],
  rideTrends: [
    { month: "Mai", completed: 820, cancelled: 62 },
    { month: "Juin", completed: 940, cancelled: 55 },
    { month: "Juil", completed: 1012, cancelled: 74 },
    { month: "Août", completed: 980, cancelled: 69 },
    { month: "Sept", completed: 1104, cancelled: 57 },
    { month: "Oct", completed: 1186, cancelled: 61 },
    { month: "Nov", completed: 1284, cancelled: 52 },
  ],
  subscriptionHealth: [
    { plan: "Essai", users: 312, arpu: 12, trend: -4 },
    { plan: "Actif", users: 1_842, arpu: 38, trend: 9 },
    { plan: "Premium", users: 264, arpu: 86, trend: 14 },
  ],
  alerts: [
    {
      id: "alert-01",
      type: "kyc",
      message: "8 chauffeurs en attente depuis plus de 24h",
      severity: "medium",
      timestamp: "2025-11-17T08:30:00Z",
    },
    {
      id: "alert-02",
      type: "support",
      message: "3 tickets VIP à traiter avant 10h",
      severity: "high",
      timestamp: "2025-11-17T07:50:00Z",
    },
    {
      id: "alert-03",
      type: "payment",
      message: "Webhook Airtel Money instable, monitoring activé",
      severity: "low",
      timestamp: "2025-11-17T07:15:00Z",
    },
  ],
  activeZones: [
    { id: "zone-gn", name: "Gombe → Ngaliema", rides: 312, occupancy: 86, status: "stable" },
    { id: "zone-ls", name: "Lemba → Ndjili", rides: 228, occupancy: 72, status: "watch" },
    { id: "zone-ms", name: "Masina → Centre-ville", rides: 194, occupancy: 64, status: "watch" },
    { id: "zone-kt", name: "Kintambo → Gombe", rides: 148, occupancy: 91, status: "critical" },
  ],
  topDrivers: [
    { id: "drv-01", name: "Stéphane B.", score: 98, completed: 142, rating: 4.97 },
    { id: "drv-02", name: "Claudia M.", score: 95, completed: 133, rating: 4.93 },
    { id: "drv-03", name: "Junior L.", score: 92, completed: 128, rating: 4.88 },
  ],
  kycQueueShortlist: kycDocumentsPayload.slice(0, 3),
};

export const usersPayload: UserRecord[] = [
  {
    id: "USR-901",
    name: "Sandrine Kabeya",
    email: "sandrine.k@zwanga.cd",
    phone: "+243 829 555 410",
    plan: "Actif",
    rides: 182,
    rating: 4.92,
    status: "actif",
    lastRide: "2025-11-17T07:50:00Z",
  },
  {
    id: "USR-902",
    name: "Patrick Mumbere",
    email: "patrick.m@zwanga.cd",
    phone: "+243 977 225 148",
    plan: "Actif",
    rides: 98,
    rating: 4.81,
    status: "actif",
    lastRide: "2025-11-17T06:30:00Z",
  },
  {
    id: "USR-903",
    name: "Prisca Ngalula",
    email: "prisca.ng@zwanga.cd",
    phone: "+243 814 300 789",
    plan: "Essai",
    rides: 12,
    rating: 4.65,
    status: "en revue",
    lastRide: "2025-11-15T10:22:00Z",
  },
  {
    id: "USR-904",
    name: "David Luwezi",
    email: "david.l@zwanga.cd",
    phone: "+243 991 220 500",
    plan: "Actif",
    rides: 244,
    rating: 4.98,
    status: "actif",
    lastRide: "2025-11-17T08:05:00Z",
  },
  {
    id: "USR-905",
    name: "Stéphanie Badika",
    email: "stephanie.b@zwanga.cd",
    phone: "+243 829 990 114",
    plan: "Expiré",
    rides: 65,
    rating: 4.41,
    status: "suspendu",
    lastRide: "2025-10-29T14:15:00Z",
  },
];

export const ridesPayload: RideRecord[] = [
  {
    id: "RIDE-9001",
    driver: "Stéphane B.",
    departure: "Gombe",
    arrival: "Ngaliema",
    status: "actif",
    seats: 3,
    price: 8,
    departureTime: "2025-11-17T08:15:00Z",
    demandLevel: "haut",
  },
  {
    id: "RIDE-9002",
    driver: "Claudia M.",
    departure: "Lemba",
    arrival: "Ndjili",
    status: "terminé",
    seats: 2,
    price: 6.5,
    departureTime: "2025-11-17T07:40:00Z",
    demandLevel: "moyen",
  },
  {
    id: "RIDE-9003",
    driver: "Junior L.",
    departure: "Kintambo",
    arrival: "Gombe",
    status: "annulé",
    seats: 4,
    price: 7.5,
    departureTime: "2025-11-17T07:10:00Z",
    demandLevel: "haut",
  },
  {
    id: "RIDE-9004",
    driver: "Armand K.",
    departure: "Masina",
    arrival: "Centre-ville",
    status: "actif",
    seats: 3,
    price: 9.5,
    departureTime: "2025-11-17T08:05:00Z",
    demandLevel: "haut",
  },
  {
    id: "RIDE-9005",
    driver: "Linda K.",
    departure: "Kasa-Vubu",
    arrival: "Gombe",
    status: "terminé",
    seats: 1,
    price: 5.5,
    departureTime: "2025-11-17T06:55:00Z",
    demandLevel: "bas",
  },
];

export const subscriptionsPayload: SubscriptionPlan[] = [
  {
    id: "SUB-ESSAI",
    name: "Plan Essai",
    tier: "Essai",
    price: 0,
    riders: 320,
    renewalRate: 48,
    paymentProviders: ["Orange Money"],
    lastInvoice: "2025-11-15",
  },
  {
    id: "SUB-PRO",
    name: "Plan Pro",
    tier: "Pro",
    price: 39,
    riders: 1480,
    renewalRate: 82,
    paymentProviders: ["Orange Money", "M-Pesa", "Airtel Money"],
    lastInvoice: "2025-11-16",
  },
  {
    id: "SUB-ENT",
    name: "Plan Entreprise",
    tier: "Entreprise",
    price: 89,
    riders: 260,
    renewalRate: 91,
    paymentProviders: ["Banque", "Visa Business"],
    lastInvoice: "2025-11-10",
  },
];

export const reportsPayload: IncidentReport[] = [
  {
    id: "REP-7001",
    type: "sécurité",
    reporter: "Cliente - Mireille T.",
    description: "Conduite brusque signalée entre Lemba et Ndjili.",
    status: "en cours",
    priority: "haute",
    createdAt: "2025-11-17T05:50:00Z",
  },
  {
    id: "REP-7002",
    type: "paiement",
    reporter: "Chauffeur - K. Luyeye",
    description: "Reversement Airtel Money en attente depuis 36h.",
    status: "ouvert",
    priority: "moyenne",
    createdAt: "2025-11-16T19:10:00Z",
  },
  {
    id: "REP-7003",
    type: "comportement",
    reporter: "Passager - Eric S.",
    description: "Mauvais accueil du chauffeur, demande de suivi.",
    status: "résolu",
    priority: "basse",
    createdAt: "2025-11-14T16:25:00Z",
  },
];

export const supportPayload: SupportTicket[] = [
  {
    id: "SUP-3001",
    channel: "WhatsApp",
    requester: "VIP - Sidonie",
    topic: "Assistance corporate Gombe",
    status: "en cours",
    sla: "00:32",
    lastUpdate: "2025-11-17T08:02:00Z",
  },
  {
    id: "SUP-3002",
    channel: "Email",
    requester: "Orange Money",
    topic: "Validation webhook",
    status: "nouveau",
    sla: "00:45",
    lastUpdate: "2025-11-17T07:58:00Z",
  },
  {
    id: "SUP-3003",
    channel: "Chat",
    requester: "Passager - Arsène",
    topic: "Facture PDF",
    status: "clos",
    sla: "—",
    lastUpdate: "2025-11-16T22:40:00Z",
  },
];

export const notificationsPayload: NotificationItem[] = [
  {
    id: "NTF-01",
    title: "KYC prioritaire",
    category: "KYC",
    description: "Grace Mwamba a chargé ses pièces, délai 30 min.",
    createdAt: "2025-11-17T08:10:00Z",
    read: false,
  },
  {
    id: "NTF-02",
    title: "Signalement critique",
    category: "Signalement",
    description: "Incident sécurité sur la zone Ndjili.",
    createdAt: "2025-11-17T07:55:00Z",
    read: false,
  },
  {
    id: "NTF-03",
    title: "Nouvel utilisateur validé",
    category: "Utilisateur",
    description: "David Luwezi vient d'activer son compte entreprise.",
    createdAt: "2025-11-17T07:35:00Z",
    read: true,
  },
  {
    id: "NTF-04",
    title: "Ticket support clos",
    category: "Support",
    description: "Incident #SUP-3003 résolu par Linda.",
    createdAt: "2025-11-16T22:40:00Z",
    read: true,
  },
];

export const profilePayload: AdminProfile = {
  id: "ADM-01",
  name: "Eugène Bosuku",
  role: "Head of Operations",
  email: "eugene.bosuku@zwanga.cd",
  phone: "+243 820 900 321",
  lastConnection: "2025-11-17T07:45:00Z",
  stats: {
    kycValidated: 168,
    ticketsResolved: 312,
    actionsThisWeek: 58,
    securityLevel: "Renforcé",
  },
  notifications: {
    email: true,
    sms: false,
    push: true,
  },
  security: {
    twoFactorEnabled: true,
    lastPasswordChange: "2025-08-12",
    trustedDevices: ["MacBook Pro Kinshasa", "iPhone 15 Pro"],
  },
};

